"""Initial migration

Revision ID: 5802dc7c66be
Revises: 
Create Date: 2024-09-11 13:27:09.889558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5802dc7c66be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waiter')
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_type', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_column('shift_type')

    op.create_table('waiter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='waiter_pkey'),
    sa.UniqueConstraint('email', name='waiter_email_key')
    )
    # ### end Alembic commands ###
